In [1]:
import gym
import itertools
import matplotlib
import numpy as np
import sys
import sklearn.pipeline
import sklearn.preprocessing
from sklearn.linear_model import SGDRegressor
from sklearn.kernel_approximation import RBFSampler
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import sgd


Using TensorFlow backend.


In [3]:
env = gym.envs.make("MountainCar-v0")


[2017-07-03 12:10:51,061] Making new env: MountainCar-v0


In [1]:
class Neural_Function_Approximator():
    """
    Value Function approximator. 
    """
    
    def __init__(self):
        self.model = Sequential()
        self.model.add(Dense(hidden_size, input_shape=(2,), activation='relu'))
        self.model.add(Dense(hidden_size, activation='relu'))
        self.model.add(Dense(num_actions))
        self.model.compile(sgd(lr=.2), "mse")
            
    
    
    def predict(self, s, a=None):
       
        return self.model.predict(s)

    def collect_data(self ,state, best_action, reward, next_state, done):
        exp_replay.remember(state, best_action, reward, next_state, done)
        
    def update(self, s, a, y):
        """
        Updates the estimator parameters for a given state and action towards
        the target y.
        """
        exp_replay.remember(state, best_action, reward, next_state, done)
        inputs, targets = exp_replay.get_batch(self.model, batch_size=batch_size)
        self.model.train_on_batch(inputs, targets)
        loss += model.train_on_batch(inputs, targets)[0]

In [2]:
class ExperienceReplay(object):
    def __init__(self, max_memory=100, discount=0.1):
        self.max_memory = max_memory
        self.memory = list()
        self.discount = discount

    def remember(self, state, best_action, reward, next_state, done):
        # memory[i] = [state, best_action, reward, next_state, done]
        self.memory.append([state, best_action, reward, next_state, done])
        if len(self.memory) > self.max_memory:
            del self.memory[0]

    def get_batch(self, model, batch_size=10):
        len_memory = len(self.memory)
        num_actions = env.action_space.n
        env_dim = len(env.observation_space.sample())
        inputs = np.zeros((min(len_memory, batch_size), env_dim))
        targets = np.zeros((inputs.shape[0], num_actions))
        for i, idx in enumerate(np.random.randint(0, len_memory,
                                                  size=inputs.shape[0])):
            state, best_action, reward, next_state, done = self.memory[idx]
            
            

            inputs[i:i+1] = state
            targets[i] = model.predict(state)[0]
            Q_sa = np.max(model.predict(next_state)[0])
            if done:  
                targets[i, action_t] = reward_t
            else:
         
                targets[i, best_action] = reward + self.discount * Q_sa
        return inputs, targets

In [55]:
def q_learning(env, estimator, num_episodes, discount_factor=1.0, epsilon=0.1, epsilon_decay=1.0):

    
    episode_lengths=np.zeros(num_episodes)
    episode_rewards=np.zeros(num_episodes)   
    
    for i_episode in range(num_episodes):
        
        print (i_episode)
        
        # Reset the environment and pick the first action
        state = env.reset()
         
        for t in itertools.count():
                        
            print(t)
            if np.random.rand() <= epsilon*epsilon_decay**i_episode:
               best_action = np.random.randint(0, env.action_space.n, size=1)[0]
            else:
               q = estimator.predict(state)
               best_action = np.argmax(q)
            print(state)
            print(estimator.predict(state))  
            print(np.argmax(estimator.predict(state)))
            print(best_action)
            
            # Take a step
            print(env.step(best_action))
            next_state, reward, done, _ = env.step(best_action)
            
           
            # Update lists
            episode_rewards[i_episode] += reward
            episode_lengths[i_episode] = t
            #print(sum(episode_lengths))
            
            # Update
            q_values_next = estimator.predict(next_state)
            #print(q_values_next)
          
            # Q-Value target
            td_target = reward + discount_factor * np.max(q_values_next)
            

            # adapt model
            inputs, targets = exp_replay.get_batch(model, batch_size=batch_size)
            
            if estimator == 'Neural_Function_Approximator':
               estimator.update(state)
            else:
               estimator.update(state, best_action, td_target)
                
            if done:
                break
                
            state2 = next_state
            state =next_state
            
            
            
            print(state2)
    
    return [episode_rewards ,episode_lengths]

In [52]:
num_actions = 3  # [move_left, stay, move_right]
max_memory = 500
hidden_size = 100
batch_size = 50
input_size = 2
exp_replay = ExperienceReplay(max_memory=max_memory)

In [53]:
estimator = Neural_Function_Approximator()

In [3]:
self.model = Sequential()
        self.model.add(Dense(hidden_size, input_shape=(2,), activation='relu'))
        self.model.add(Dense(hidden_size, activation='relu'))
        self.model.add(Dense(num_actions))
        self.model.compile(sgd(lr=.2), "mse")

IndentationError: unexpected indent (<ipython-input-3-f7357ccad28d>, line 2)

In [56]:
q_learning(env, estimator, 100, epsilon=0.1)
            
  

0
0


ValueError: Error when checking : expected dense_20_input to have shape (None, 2) but got array with shape (2, 1)

In [40]:
model = Sequential()
model.add(Dense(hidden_size, input_shape=(2,1 ), activation='relu'))
model.add(Dense(hidden_size, activation='relu'))
model.add(Dense(num_actions))
model.compile(sgd(lr=.2), "mse")

In [146]:
env.reset()
for _ in range(0,100):
   print(env.step(1))



(array([-0.42476596, -0.00073571]), -1.0, False, {})
(array([-0.4262321 , -0.00146614]), -1.0, False, {})
(array([-0.42841815, -0.00218605]), -1.0, False, {})
(array([-0.4313084 , -0.00289024]), -1.0, False, {})
(array([-0.43488201, -0.00357361]), -1.0, False, {})
(array([-0.43911317, -0.00423116]), -1.0, False, {})
(array([-0.44397121, -0.00485804]), -1.0, False, {})
(array([-0.4494208 , -0.00544958]), -1.0, False, {})
(array([-0.45542213, -0.00600134]), -1.0, False, {})
(array([-0.46193124, -0.00650911]), -1.0, False, {})
(array([-0.46890022, -0.00696898]), -1.0, False, {})
(array([-0.4762776 , -0.00737738]), -1.0, False, {})
(array([-0.48400869, -0.0077311 ]), -1.0, False, {})
(array([-0.49203602, -0.00802732]), -1.0, False, {})
(array([-0.50029971, -0.00826369]), -1.0, False, {})
(array([-0.508738  , -0.00843829]), -1.0, False, {})
(array([-0.51728771, -0.00854971]), -1.0, False, {})
(array([-0.52588475, -0.00859704]), -1.0, False, {})
(array([-0.53446465, -0.0085799 ]), -1.0, Fals

In [161]:
env.action_space.n

3

In [2]:
import gym
import itertools
import matplotlib
import numpy as np
import sys
import sklearn.pipeline
import sklearn.preprocessing
from sklearn.linear_model import SGDRegressor
from sklearn.kernel_approximation import RBFSampler
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import sgd

In [3]:
class ExperienceReplay(object):
    def __init__(self, max_memory=100, discount=.9):
        self.max_memory = max_memory
        self.memory = list()
        self.discount = discount

    def remember(self,state, best_action, reward, next_state, done):
        # memory[i] = [[state_t, action_t, reward_t, state_t+1], game_over?]
        self.memory.append([state, best_action, reward, next_state, done])
        if len(self.memory) > self.max_memory:
            del self.memory[0]

    def get_batch(self, model, batch_size=10):
        len_memory = len(self.memory)
        num_actions = model.output_shape[-1]
        # env_dim = self.memory[0][0][0].shape[1]
        env_dim = len(env.observation_space.sample())
        inputs = np.zeros((min(len_memory, batch_size), env_dim))
        targets = np.zeros((inputs.shape[0], num_actions))
        for i, idx in enumerate(np.random.randint(0, len_memory,
                                                  size=inputs.shape[0])):
            state_t, action_t, reward_t, state_tp1 = self.memory[idx][0:4]
            done = self.memory[idx][4]

            inputs[i:i+1] = state_t
            # There should be no target values for actions not taken.
            # Thou shalt not correct actions not taken #deep
            targets[i] = model.predict(state_t.reshape((1,2)))[0]
            Q_sa = np.max(model.predict(state_tp1.reshape((1,2)))[0])
            if done:  # if game_over is True
                targets[i, action_t] = reward_t
            else:
                # reward_t + gamma * max_a' Q(s', a')
                targets[i, action_t] = reward_t + self.discount * Q_sa
        return inputs, targets



In [4]:

epsilon = .1  # exploration
num_actions = 3  # [move_left, stay, move_right]
epoch = 100000
max_memory = 500
hidden_size = 100
batch_size = 50
input_size = 2
done = False


    

 


In [5]:
model = Sequential()
model.add(Dense(hidden_size, input_dim=2, activation='relu'))
    # model.add(Dense(hidden_size, input_shape=(2,1)))
model.add(Dense(hidden_size, activation='relu'))
model.add(Dense(num_actions))
model.compile(sgd(lr=.2), "mse")

In [6]:
a = env.reset()
b = a.reshape((1, 2))
model.predict(b)
#model.output_shape[-1]

NameError: name 'env' is not defined

In [8]:
env = gym.envs.make("MountainCar-v0")
#a = env.reset()
#env.step(0)

[2017-07-05 01:18:47,091] Making new env: MountainCar-v0


In [7]:
    # Define environment/game
env = gym.envs.make("MountainCar-v0")

    # Initialize experience replay object
exp_replay = ExperienceReplay(max_memory=max_memory)

    # Train
win_cnt = 0
episode_length = np.zeros(epoch)
episode_rewards = np.zeros(epoch)
loss_list = []
for e in range(epoch):
        print(e)
       
        loss = 0.
        done = False
        # get initial input
        input_t = env.reset().reshape((1, 2))
        print ("win count is {}".format(win_cnt))
        step = 0
        for t in itertools.count():
            
            episode_length[e] = t
            
            input_tm1 = input_t.reshape((1,2))
            step += 1
                # get next action
            if np.random.rand() <= epsilon:
               action = np.random.randint(0, num_actions, size=1)[0]
            else:
               q = model.predict(input_tm1)
               action = np.argmax(q[0])
            

                # apply action, get rewards and new state
            input_t, reward, done, _ = env.step(action)
            if done:
                break
            if reward == 0:
               win_cnt += 1
            episode_rewards[e] += reward
            
               # store experience
            exp_replay.remember(input_t, action, reward, input_tm1,done)
            
            
            inputs, targets = exp_replay.get_batch(model, batch_size=batch_size)
        print(model.train_on_batch(inputs.reshape((np.shape(inputs)[0],2)), targets)) 
        iter_loss = model.train_on_batch(inputs.reshape((np.shape(inputs)[0],2)), targets)
        loss_list.append(iter_loss)
        loss += model.train_on_batch(inputs.reshape((np.shape(inputs)[0],2)), targets)

[2017-07-05 01:22:16,923] Making new env: MountainCar-v0


0
win count is 0
0.331845
1
win count is 0
0.206696
2
win count is 0
0.19584
3
win count is 0
0.277899
4
win count is 0
0.151528
5
win count is 0
0.172115
6
win count is 0
0.24541
7
win count is 0
0.145852
8
win count is 0
0.168186
9
win count is 0
0.138046
10
win count is 0
0.12594
11
win count is 0
0.5336
12
win count is 0
181.023
13
win count is 0
nan
14
win count is 0
nan
15
win count is 0
nan
16
win count is 0
nan
17
win count is 0
nan
18
win count is 0


KeyboardInterrupt: 

In [9]:
loss

0.0

In [20]:
import json
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import sgd
from MountainCar import MountainCar



if __name__ == "__main__":
    # parameters
    epsilon = .1  # exploration
    num_actions = 3  # [move_left, stay, move_right]
    epoch = 1000
    max_memory = 500
    hidden_size = 100
    batch_size = 50
    input_size = 2

    Xrange = [-1.5, 0.55]
    Vrange = [-0.7, 0.7]
    start = [-0.5, 0.0]
    goal = [0.45]

    model = Sequential()
    model.add(Dense(hidden_size, input_shape=(2, ), activation='relu'))
    # model.add(Dense(hidden_size, input_shape=(2,1)))
    model.add(Dense(hidden_size, activation='relu'))
    model.add(Dense(num_actions))
    model.compile(sgd(lr=.2), "mse")

    # If you want to continue training from a previous model, just uncomment the line bellow
    # model.load_weights("model.h5")

    # Define environment/game
    env = MountainCar(start, goal, Xrange, Vrange)

    # Initialize experience replay object
    exp_replay = ExperienceReplay(max_memory=max_memory)

    # Train
    

ImportError: No module named MountainCar

In [21]:
class ExperienceReplay(object):
    def __init__(self, max_memory=100, discount=.9):
        self.max_memory = max_memory
        self.memory = list()
        self.discount = discount

    def remember(self, states, game_over):
        # memory[i] = [[state_t, action_t, reward_t, state_t+1], game_over?]
        self.memory.append([states, game_over])
        if len(self.memory) > self.max_memory:
            del self.memory[0]

    def get_batch(self, model, batch_size=10):
        len_memory = len(self.memory)
        num_actions = model.output_shape[-1]
        # env_dim = self.memory[0][0][0].shape[1]
        env_dim = self.memory[0][0][0].shape[1]
        inputs = np.zeros((min(len_memory, batch_size), env_dim))
        targets = np.zeros((inputs.shape[0], num_actions))
        for i, idx in enumerate(np.random.randint(0, len_memory,
                                                  size=inputs.shape[0])):
            state_t, action_t, reward_t, state_tp1 = self.memory[idx][0]
            game_over = self.memory[idx][1]

            inputs[i:i+1] = state_t
            # There should be no target values for actions not taken.
            # Thou shalt not correct actions not taken #deep
            targets[i] = model.predict(state_t)[0]
            Q_sa = np.max(model.predict(state_tp1)[0])
            if game_over:  # if game_over is True
                targets[i, action_t] = reward_t
            else:
                # reward_t + gamma * max_a' Q(s', a')
                targets[i, action_t] = reward_t + self.discount * Q_sa
        return inputs, targets

In [ ]:
win_cnt = 0
for e in range(epoch):
    loss = 0.
    
    done = False
        # get initial input
    input_t = env.reset()

    step = 0
    while (not game_over):
            input_tm1 = input_t
            step += 1
            # get next action
            if np.random.rand() <= epsilon:
                action = np.random.randint(0, num_actions, size=1)
            else:
                q = model.predict(input_tm1)
                action = np.argmax(q[0])

            # apply action, get rewards and new state
            input_t, reward, game_over = env.act(action)
            if reward == 100:
                win_cnt += 1

            # store experience
            exp_replay.remember([input_tm1, action, reward, input_t], game_over)

            # adapt model
            inputs, targets = exp_replay.get_batch(model, batch_size=batch_size)

            loss += model.train_on_batch(inputs, targets)[0]
        print("Step {} Epoch {:03d}/999 | Loss {:.4f} | Win count {}".format(step, e, loss, win_cnt))

    # Save trained model weights and architecture, this will be used by the visualization code
    model.save_weights("model.h5", overwrite=True)
    with open("model.json", "w") as outfile:
        json.dump(model.to_json(), outfile)

In [4]:

env = gym.envs.make("MountainCar-v0")
env.reset()
a = env.step(0)
print(a)

[2017-07-04 17:08:56,687] Making new env: MountainCar-v0


(array([-0.44660491, -0.00158389]), -1.0, False, {})


In [11]:


#env_low = env.observation_space.low
#env_high = env.observation_space.high
env_dx = (env_high - env_low) / 50
c = int((a[0][0] - env_low[0])/env_dx[0])
#b = int((obs[1] - env_low[1])/env_dx[1])
  


In [14]:
#np.random.choice(env.action_space.n, size=(20,20))
q_table = np.zeros((20, 20, 3))

In [15]:
q_table

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       ..., 
       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,